# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 创建目录并移动文件到 bark-notify
      run: |
        # 创建目录
        mkdir bark-notify
        # 将当前目录下所有非隐藏文件/目录移动到 bark-notify（排除目录本身）
        find . -maxdepth 1 -not -name '.' -not -name 'bark-notify' -exec mv {} bark-notify/ \;
    - name: 下载 dify-plugin-linux-amd64 程序
      run: |
        wget https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.6/dify-plugin-linux-amd64
    - name: 赋予可执行权限
      run: chmod +x dify-plugin-linux-amd64
    - name: 运行 dify-plugin
      run: |
        # 进入项目根目录（确保路径正确）
        ./dify-plugin-linux-amd64 plugin package bark-notify
    - name: 列出文件
      run: ls -la
