# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: download dify-plugin-linux-amd64 app
      run: |
        wget https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.6/dify-plugin-linux-amd64
    - name: Grant executable permissions
      run: chmod +x dify-plugin-linux-amd64
    - name: Create a temporary directory and run dify-plugin
      run: |
        mkdir plugin_temp
        cp -r ./* plugin_temp/
        ./dify-plugin-linux-amd64 plugin package plugin_temp
    - name: list files
      run: ls -la

